version: '3'
services:
  db:
    image: postgres
    ports:
      - 5430:5432
    environment:
      POSTGRES_USER: postgres
      POSTGRES_PASSWORD: password
      POSTGRES_DB: test
    volumes:
      - db_vol:/var/lib/postgresql/data
      - ../postgres/init_scripts/:/docker-entrypoint-initdb.d/
      - ../input_data/:/opt/input_data/

volumes:
  db_vol: